export const SEARCHBOX_KEYWORD_SET = 'SEARCHBOX_KEYWORD_SET'
export const SEARCHBOX_KEYWORD_RESET = 'SEARCHBOX_KEYWORD_RESET'

export const SEARCHBOX_CATEGORY_SET = 'SEARCHBOX_CATEGORY_SET'
export const SEARCHBOX_CATEGORY_RESET = 'SEARCHBOX_CATEGORY_RESET'

export const SEARCHBOX_BRAND_SET = 'SEARCHBOX_BRAND_SET'
export const SEARCHBOX_BRAND_RESET = 'SEARCHBOX_BRAND_RESET'

export const SEARCHBOX_FILTER_SET = 'SEARCHBOX_FILTER_SET'
export const SEARCHBOX_FILTER_RESET = 'SEARCHBOX_FILTER_RESET'

