# Generated by Django 3.1.7 on 2021-04-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210415_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesList',
            fields=[
                ('category', models.CharField(max_length=20)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorieslist'),
        ),
    ]
